services:
  db:
    image: postgres:16
    container_name: iteh_uvoznici_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: iteh_uvoznici
    ports:
      - "5432:5432"
    volumes:
      - iteh_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d iteh_uvoznici"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: iteh_uvoznici_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      #               protokol://username:password@host:port/db
      DATABASE_URL: postgresql://app:app@db:5432/iteh_uvoznici
      JWT_SECRET: iteh_uvoznici_dev_secret

volumes:
  iteh_pg_data: